import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { addCoach, deleteCoach, getAdminCoaches, getAdminSeats } from "../services/api";

export default function CoachesPage() {
  const { trainId } = useParams(); const token = localStorage.getItem("token"); const [data, setData] = useState(null); const [seats, setSeats] = useState(null); const [form, setForm] = useState({ coach_name: "", seats: "", type: "" }); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const types = ["shulov", "shovan", "s_chair", "f_seat", "f_chair", "snigdha", "f_berth", "ac_s", "ac_berth"];
  const load = () => getAdminCoaches(trainId, token).then(setData).catch((err) => setError(err.message));
  useEffect(() => { load(); }, [trainId]);
  const viewSeats = async (coachId) => { try { setSeats(await getAdminSeats(coachId, localStorage.getItem("token"))); } catch (err) { setError(err.message); } };
  const createCoach = async (event) => { event.preventDefault(); try { await addCoach(Number(trainId), form.coach_name, Number(form.seats), form.type, token); setForm({ coach_name: "", seats: "", type: "" }); setMessage("Coach added with seats"); await load(); } catch (err) { setError(err.message); } };
  const removeCoach = async (coach) => { if (!window.confirm(`Delete coach "${coach.coach_name}"? Coaches with booking records are protected.`)) return; try { await deleteCoach(coach.coach_id, token); setMessage("Coach deleted"); setSeats(null); await load(); } catch (err) { setError(err.message); } };
  if (error) return <div className="admin-shell"><div className="admin-empty">{error}</div></div>;
  if (!data) return <div className="admin-shell"><div className="admin-empty">Loading coaches...</div></div>;
  return <div className="admin-shell"><main className="admin-content narrow"><Link className="back-link" to="/admin">← Back to trains</Link><p className="eyebrow">COACH MANAGEMENT</p><h1>{data.train.train_name}</h1>{message && <div className="admin-alert success">{message}</div>}{error && <div className="admin-alert error">{error}</div>}<form className="admin-toolbar coach-form" onSubmit={createCoach}><label>Coach name<input value={form.coach_name} onChange={(event) => setForm({ ...form, coach_name: event.target.value })} placeholder="e.g. C1" required /></label><label>Seat count<input type="number" min="1" value={form.seats} onChange={(event) => setForm({ ...form, seats: event.target.value })} required /></label><label>Coach type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} required><option value="">Select type</option>{types.map((type) => <option key={type} value={type}>{type}</option>)}</select></label><button className="admin-primary" type="submit">Add coach</button></form><section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Coach</th><th>Type</th><th>Seats configured</th><th>Action</th></tr></thead><tbody>{data.coaches.map((coach) => <tr key={coach.coach_id}><td><strong>{coach.coach_name}</strong></td><td><span className="type-pill">{coach.type}</span></td><td>{coach.seat_count} / {coach.seats}</td><td><button className="text-button" onClick={() => viewSeats(coach.coach_id)}>View seats</button><button className="danger-button" onClick={() => removeCoach(coach)}>Remove</button></td></tr>)}</tbody></table></section>{seats && <section className="seat-panel"><div><p className="eyebrow">SEAT INVENTORY</p><h2>{seats.coach.coach_name} · {seats.coach.type}</h2></div><div className="seat-grid">{seats.seats.map((seat) => <span className={`seat ${seat.reservation_status}`} key={seat.seat_id}>{seat.seat_number}</span>)}</div></section>}</main></div>;
}