import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getAdminOverview, getAdminRoute, updateRoute } from "../services/api";

export default function RoutePage() {
  const { routeId } = useParams(); const token = localStorage.getItem("token"); const [data, setData] = useState(null); const [stations, setStations] = useState([]); const [selectedStation, setSelectedStation] = useState(""); const [arrivalTime, setArrivalTime] = useState(""); const [departureTime, setDepartureTime] = useState(""); const [distance, setDistance] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { try { const [route, overview] = await Promise.all([getAdminRoute(routeId, token), getAdminOverview(token)]); setData(route); setStations(overview.stations); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, [routeId]);
  const saveStations = async (nextStations) => { try { await updateRoute(routeId, nextStations.map((station, index) => ({ station_id: station.station_id, distance_km: Number(station.distance_km) || 0, arrival_time: station.arrival_time || null, departure_time: station.departure_time || null, sequence_no: index + 1 })), token); setMessage("Route stations updated"); await load(); } catch (err) { setError(err.message); } };
  const addStation = () => { const station = stations.find((item) => String(item.station_id) === selectedStation); if (!station || data.stations.some((item) => item.station_id === station.station_id) || distance === "") return; saveStations([...data.stations, { ...station, distance_km: distance, arrival_time: arrivalTime, departure_time: departureTime }]); setSelectedStation(""); setArrivalTime(""); setDepartureTime(""); setDistance(""); };
  const removeStation = (stationId) => { if (data.stations.length <= 2) { setError("A route must keep at least two stations."); return; } if (window.confirm("Remove this station from the route?")) saveStations(data.stations.filter((station) => station.station_id !== stationId)); };
  if (error) return <div className="admin-shell"><div className="admin-empty">{error}</div></div>;
  if (!data) return <div className="admin-shell"><div className="admin-empty">Loading route...</div></div>;
  return <div className="admin-shell"><main className="admin-content narrow"><Link className="back-link" to="/admin">← Back to trains</Link><p className="eyebrow">ROUTE {data.route.route_id}</p><h1>{data.route.from_station} <span className="route-arrow">→</span> {data.route.to_station}</h1><p className="muted">From and to are derived from the ordered station list.</p>{message && <div className="admin-alert success">{message}</div>}{error && <div className="admin-alert error">{error}</div>}<section className="admin-toolbar route-tools"><label>Station<select value={selectedStation} onChange={(event) => setSelectedStation(event.target.value)}><option value="">Select a station</option>{stations.filter((station) => !data.stations.some((item) => item.station_id === station.station_id)).map((station) => <option key={station.station_id} value={station.station_id}>{station.station_name} · {station.city}</option>)}</select></label><label>Arrival<input type="time" value={arrivalTime} onChange={(event) => setArrivalTime(event.target.value)} /></label><label>Departure<input type="time" value={departureTime} onChange={(event) => setDepartureTime(event.target.value)} /></label><label>Distance (km)<input type="number" min="0" step="0.01" value={distance} onChange={(event) => setDistance(event.target.value)} required /></label><button className="admin-primary" onClick={addStation} disabled={!selectedStation || distance === ""}>Add to route</button></section><section className="route-list">{data.stations.map((station) => <div className="route-row" key={station.station_id}><strong>{station.sequence_no}</strong><div><b>{station.station_name}</b><span>{station.city || ""} · arrival {station.arrival_time || "not set"} · departure {station.departure_time || "not set"}</span></div><small>{station.distance_km} km <button className="danger-button" onClick={() => removeStation(station.station_id)}>Remove</button></small></div>)}</section></main></div>;
}